config/routes.rb
# == Route Map
#
#           Prefix Verb   URI Pattern                      Controller#Action
#            items GET    /items(.:format)                 items#index
#                  POST   /items(.:format)                 items#create
#         new_item GET    /items/new(.:format)             items#new
#        edit_item GET    /items/:id/edit(.:format)        items#edit
#             item GET    /items/:id(.:format)             items#show
#                  PATCH  /items/:id(.:format)             items#update
#                  PUT    /items/:id(.:format)             items#update
#                  DELETE /items/:id(.:format)             items#destroy
#     sales_orders GET    /sales_orders(.:format)          sales_orders#index
#                  POST   /sales_orders(.:format)          sales_orders#create
#  new_sales_order GET    /sales_orders/new(.:format)      sales_orders#new
# edit_sales_order GET    /sales_orders/:id/edit(.:format) sales_orders#edit
#      sales_order GET    /sales_orders/:id(.:format)      sales_orders#show
#                  PATCH  /sales_orders/:id(.:format)      sales_orders#update
#                  PUT    /sales_orders/:id(.:format)      sales_orders#update
#                  DELETE /sales_orders/:id(.:format)      sales_orders#destroy
#             root GET    /                                pages#home
# 

Rails.application.routes.draw do


  resources :items, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :sales_orders, :only => [:index, :show, :new, :create, :edit, :update, :destroy]

  root :to => "pages#home"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  part_number :text
#  image       :text
#  list_price  :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Item < ApplicationRecord
  has_many :sales_order_details
end

app/models/sales_order.rb
# == Schema Information
#
# Table name: sales_orders
#
#  id                 :integer          not null, primary key
#  quote_date         :date
#  sale_date          :date
#  customer_PO_number :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class SalesOrder < ApplicationRecord
  has_many :sales_order_details
end

app/models/sales_order_detail.rb
# == Schema Information
#
# Table name: sales_order_details
#
#  id             :integer          not null, primary key
#  item_id        :integer
#  sales_order_id :integer
#  quantity       :integer
#  unit_price     :decimal(, )
#  despatch_date  :date
#

class SalesOrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :sales_order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.create item_params
    if item.save
      redirect_to item
    else
      redirect_to root
      # later we'll make a better landing page for failed save action.
    end
  end

  def edit
    @item = Item.find params[:id]
  end

  def update
    item = Item.find params[:id]
    item.update item_params
    redirect_to item
  end

  def show
    @item = Item.find_by :id => params[:id]
  end

  def destroy
    items = Item.find params[:id]
    items.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:part_number, :list_price)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sales_orders_controller.rb
class SalesOrdersController < ApplicationController

  def index
    @sales_orders = SalesOrder.all
  end

  def new
    @sales_order = SalesOrder.new
  end

  def create
    sales_order = SalesOrder.create sales_order_params
    if sales_order.save
      redirect_to sales_order
    else
      redirect_to root
      # later we'll make a better landing page for failed save action.
    end
  end


  def edit
    @sales_order = SalesOrder.find params[:id]
  end

  def update
    sales_order = SalesOrder.find params[:id]
    sales_order.update sales_order_params
    redirect_to sales_order
  end


  def show
    @sales_order = SalesOrder.find_by :id => params[:id]
  end

  def destroy
    sales_order = SalesOrder.find params[:id]
    sales_order.destroy
    redirect_to sales_order_path
  end

  private
  def sales_order_params
    params.require(:sales_order).permit(:customer_PO_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sales_orders_helper.rb
module SalesOrdersHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :multipart => true } do |f| %>

  <div class="form-group">
    <%= f.label :part_number %>
    <%= f.text_field :part_number, :class => 'form-control', :required => true   %>
  </div>

  <div class="form-group">
    <%= f.label :list_price %>
    <%= f.text_field :list_price, :class => 'form-control', :required => true   %>
  </div>

  <div class="form-group">
    <label></label>
    <%= f.submit :class => 'btn btn-info'  %>
  </div>

<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

<%= render :partial => "form" %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>


<div>
  <% @items.each do |item| %>

    <ul>
      <li>Part Number: <%= link_to item.part_number, item %></li>
    </ul>

  <% end %>
</div>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

<%= render :partial => "form" %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

<div>
  <ul>
    <li>Part Number: <%= @item.part_number %></li>
    <li>List Price: <%= @item.list_price %></li>
  </ul>
</div>

<div class="controls">
  <%= link_to 'Edit Item', edit_item_path(@item) %>
  <%= link_to 'Delete Item', @item, :method => 'delete', :data => { :confirm => 'You sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/sales_orders/_form.html.erb
<%= form_for @sales_order, :html => { :multipart => true } do |f| %>

  <div class="form-group">
    <%= f.label :id %>
    <%= f.text_field :id, :class => 'form-control'   %>
  </div>

  <div class="form-group">
    <%= f.label :customer_PO_number %>
    <%= f.text_field :customer_PO_number, :class => 'form-control', :required => true   %>
  </div>

  <div class="form-group">
    <label></label>
    <%= f.submit :class => 'btn btn-info'  %>
  </div>

<% end %>

app/views/sales_orders/edit.html.erb
<h1>SalesOrders#edit</h1>
<p>Find me in app/views/sales_orders/edit.html.erb</p>

<%= render :partial => "form" %>

app/views/sales_orders/index.html.erb
<h1>SalesOrders#index</h1>
<p>Find me in app/views/sales_orders/index.html.erb</p>

<div>
  <% @sales_orders.each do |so| %>

    <ul>
      <li>Sales Order: <%= link_to so.id, so %></li>
      <li>Customer PO Number: <%= so.customer_PO_number %></li>
    </ul>

  <% end %>
</div>

<%= link_to 'New Sales Order', new_sales_order_path %>

app/views/sales_orders/new.html.erb
<h1>SalesOrders#new</h1>
<p>Find me in app/views/sales_orders/new.html.erb</p>

<%= render :partial => "form" %>

app/views/sales_orders/show.html.erb
<h1>SalesOrders#show</h1>
<p>Find me in app/views/sales_orders/show.html.erb</p>


<div>
  <ul>
    <li>Sales Order Number: <%= @sales_order.id %></li>
    <li>Cusgomer PO Number: <%= @sales_order.customer_PO_number %></li>
  </ul>
</div>

<div class="controls">
  <%= link_to 'Edit SO', edit_sales_order_path(@sales_order) %>
  <%= link_to 'Delete SO', @sales_order, :method => 'delete', :data => { :confirm => 'You sure?' } %>
</div>